version: "2.0"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: OpenStark
    restart: unless-stopped
    container_name: openStark_db
  jenkins:
    image: jenkinsci/blueocean
    environment:
      JENKINS_AGENT_HOME: /data/project/automation/OpenStark/OpenStarkJenkins
      AGENT_HOSTS: /data/project/automation/OpenStark/OpenStarkAPI/static/files/hosts
      JAVA_OPTS: -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; 'unsafe-inline' www.google.com ajax.googleapis.com; 'unsafe-inline' 'unsafe-eval' www.google.com; img-src 'self' data:; child-src 'self'"
    user: root
    ports:
      - "8091:8080"
      - "50000:50000"
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock
      - ./OpenStarkJenkins/:/var/jenkins_home/
      - ./OpenStarkAPI/static/:/var/jenkins_home/static/
    links:
      - nginx
    restart: unless-stopped
    container_name: openStark_jenkins
  app:
    build: ./OpenStarkAPI
    volumes:
      - ./OpenStarkAPI/:/data/
    links:
      - db
    environment:
      MONITOR: "on"
    restart: unless-stopped
    container_name: openStark_app
  nginx:
    image: nginx
    volumes:
      - ./OpenStarkWEB/dist/:/usr/share/nginx/html/
      - ./OpenStarkWEB/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./OpenStarkAPI/static/:/usr/share/nginx/html/static/
    ports:
      - "8090:80"
    links:
      - app
    restart: unless-stopped
    container_name: openStark_nginx