version: "2.0"
services:
  grid:
    build: ./SeleniumGrid
    restart: unless-stopped
    ports:
      - "4444:4444"
    container_name: tfw_selenium_grid
  webdriver:
    build: ./WebDriver
    restart: unless-stopped
    ports:
      - "6080:80"
      - "5900:5900"
    links:
      - grid
    volumes:
      - ./WebDriver/hosts:/etc/host
    container_name: tfw_web_driver